### ISSUE TITLE
Impliment the design

### ISSUE THREAD

**Issue by sogasg** [colonyportal/colonyPortal#29]
Implement the design Patrick has come up with.

- [x] Login
<img width="671" alt="screen shot 2018-06-18 at 9 53 06 pm" src="https://user-images.githubusercontent.com/5522128/41750151-40048c9c-756f-11e8-8252-4eac83eff7e0.png">

- [ ] Dashboard (Colony Basics, Tasks Per Domain)
![task list details copy](https://user-images.githubusercontent.com/5522128/41750190-6c4806c6-756f-11e8-811e-91c3093de082.png)

- [ ] GitHub Task Importing
![import task](https://user-images.githubusercontent.com/5522128/41750214-8ebe93aa-756f-11e8-8769-f5a51cbbba51.png)

- [ ] Creating Task
![create a task copy 3](https://user-images.githubusercontent.com/5522128/41750237-ade4a800-756f-11e8-9fae-10b311577cfb.png)

**Comment by sogasg** [comment]
I think this should be divided into smaller tasks so that we all can work on this.

**Comment by JordanEllis6809** [comment]
Broken up into smaller tasks. Closing this.
