### ISSUE TITLE
Task Creation

### ISSUE THREAD

**Issue by JingyuZ** [colonyportal/colonyPortal#3]
_From @JordanEllis6809 on June 11, 2018 5:0_

- [x] Create a generic interface for a "task".
- [x] Display a list of a domain currently has.
- [ ] Allow the user to create a task and add it to the colony.

_Copied from original issue: JingyuZ/GithubColony#13_

**Comment by JingyuZ** [comment]
_From @JordanEllis6809 on June 11, 2018 5:15_

https://joincolony.github.io/colonyjs/docs-task-lifecycle/

https://joincolony.github.io/colonynetwork/docs-tasks/

**Comment by patrickqpan** [comment]
sure thing ill msg you on slack

**Comment by JordanEllis6809** [comment]
This task has been broken up into smaller tasks. Closing this one.
